#ifndef SDL_dynapi_h_
#define SDL_dynapi_h_
#define SDL_DYNAMIC_API 0
#endif

#define SDL_DISABLE_MM3DNOW_H
#undef __3dNOW__

#define HAVE_LIBC 1
#define _CLANG_DISABLE_CRT_DEPRECATION_WARNINGS

#define SDL_VIDEO_RENDER_D3D    0
#define SDL_VIDEO_RENDER_D3D11  0
#define SDL_VIDEO_RENDER_D3D12  0
#define SDL_AUDIO_DISABLED 1
#define SDL_FILE_DISABLED 1
#define SDL_JOYSTICK_DISABLED 1
#define SDL_HAPTIC_DISABLED 1
#define SDL_SENSOR_DISABLED 1
#define SDL_RENDER_DISABLED 1
#define SDL_TIMERS_DISABLED
#define SDL_LEAN_AND_MEAN 1

#include "SDL_config_windows.h"

#undef SDL_VIDEO_OPENGL
#undef SDL_VIDEO_OPENGL_WGL
#undef SDL_VIDEO_RENDER_OGL
#undef SDL_VIDEO_RENDER_OGL_ES2
#undef SDL_VIDEO_OPENGL_ES2
#undef SDL_VIDEO_OPENGL_EGL
#undef SDL_VIDEO_DRIVER_DUMMY
